name: Build Status

# Step 1: Build on pull-requests or pushes to main
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  # Step 2: Build the samples
  build:
    name: Build
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { regex: "Objective-C/advanced", xcode_version: "15.3" }
          - { regex: "Swift/advanced", xcode_version: "16.1" }
          - { regex: "Objective-C/admob", xcode_version: "15.3" }
          - { regex: "Swift/admob", xcode_version: "16.1" }
          - { regex: "Objective-C/admanager", xcode_version: "15.3" }
          - { regex: "Swift/admanager", xcode_version: "16.1" }
    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Select an Xcode version
        # Available Xcode versions:
        # https://github.com/actions/runner-images/blob/main/images/macos/toolsets/toolset-14.json
        run: |
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
          echo "Selected Xcode version:"
          /usr/bin/xcodebuild -version

      - name: Pod repo update
        run: pod repo update

      - name: Install xcpretty
        run: sudo gem install xcpretty

      - name: Set commit range (push to the main branch, e.g. merge)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: echo "COMMIT_RANGE="${{ github.event.before }}.."" >> $GITHUB_ENV

      - name: Set commit range (pull request)
        if: github.event_name == 'pull_request'
        run: echo "COMMIT_RANGE="HEAD~.."" >> $GITHUB_ENV

      - name: Build
        run: .github/workflows/build/build.sh
        shell: bash
        env:
          COMMIT_RANGE: ${{ env.COMMIT_RANGE }}
          REGEX: ${{ matrix.regex }}
